/*
 * generated by Xtext
 */
package org.istic.idm.xtext;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class VideoGenRuntimeModule extends org.istic.idm.xtext.AbstractVideoGenRuntimeModule {

}
