/*
 * generated by Xtext
 */
package org.istic.idm.xtext;

import org.eclipse.xtext.junit4.IInjectorProvider;
import org.istic.idm.xtext.ui.internal.VideoGenActivator;

import com.google.inject.Injector;

public class VideoGenUiInjectorProvider implements IInjectorProvider {
	
	@Override
	public Injector getInjector() {
		return VideoGenActivator.getInstance().getInjector("org.istic.idm.xtext.VideoGen");
	}
	
}
