/**
 * generated by Xtext
 */
package org.istic.idm.xtext.ui.contentassist;

import org.istic.idm.xtext.ui.contentassist.AbstractVideoGenProposalProvider;

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
@SuppressWarnings("all")
public class VideoGenProposalProvider extends AbstractVideoGenProposalProvider {
}
