/*
 * generated by Xtext
 */
package org.istic.idm.xtext.ui.contentassist.antlr;

import java.util.Collection;
import java.util.Map;
import java.util.HashMap;

import org.antlr.runtime.RecognitionException;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.AbstractContentAssistParser;
import org.eclipse.xtext.ui.editor.contentassist.antlr.FollowElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.internal.AbstractInternalContentAssistParser;

import com.google.inject.Inject;

import org.istic.idm.xtext.services.VideoGenGrammarAccess;

public class VideoGenParser extends AbstractContentAssistParser {
	
	@Inject
	private VideoGenGrammarAccess grammarAccess;
	
	private Map<AbstractElement, String> nameMappings;
	
	@Override
	protected org.istic.idm.xtext.ui.contentassist.antlr.internal.InternalVideoGenParser createParser() {
		org.istic.idm.xtext.ui.contentassist.antlr.internal.InternalVideoGenParser result = new org.istic.idm.xtext.ui.contentassist.antlr.internal.InternalVideoGenParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}
	
	@Override
	protected String getRuleName(AbstractElement element) {
		if (nameMappings == null) {
			nameMappings = new HashMap<AbstractElement, String>() {
				private static final long serialVersionUID = 1L;
				{
					put(grammarAccess.getStatementAccess().getAlternatives(), "rule__Statement__Alternatives");
					put(grammarAccess.getVideoGenAccess().getGroup(), "rule__VideoGen__Group__0");
					put(grammarAccess.getAlternativeAccess().getGroup(), "rule__Alternative__Group__0");
					put(grammarAccess.getVideoSeqAccess().getGroup(), "rule__VideoSeq__Group__0");
					put(grammarAccess.getVideoSeqAccess().getGroup_4(), "rule__VideoSeq__Group_4__0");
					put(grammarAccess.getVideoSeqAccess().getGroup_5(), "rule__VideoSeq__Group_5__0");
					put(grammarAccess.getVideoSeqAccess().getGroup_6(), "rule__VideoSeq__Group_6__0");
					put(grammarAccess.getMandatoryVideoSeqAccess().getGroup(), "rule__MandatoryVideoSeq__Group__0");
					put(grammarAccess.getOptionalVideoSeqAccess().getGroup(), "rule__OptionalVideoSeq__Group__0");
					put(grammarAccess.getVideoGenAccess().getStatementsAssignment_2(), "rule__VideoGen__StatementsAssignment_2");
					put(grammarAccess.getAlternativeAccess().getNameAssignment_1(), "rule__Alternative__NameAssignment_1");
					put(grammarAccess.getAlternativeAccess().getVideoseqsAssignment_3(), "rule__Alternative__VideoseqsAssignment_3");
					put(grammarAccess.getVideoSeqAccess().getNameAssignment_1(), "rule__VideoSeq__NameAssignment_1");
					put(grammarAccess.getVideoSeqAccess().getUrlAssignment_2(), "rule__VideoSeq__UrlAssignment_2");
					put(grammarAccess.getVideoSeqAccess().getLengthAssignment_4_1(), "rule__VideoSeq__LengthAssignment_4_1");
					put(grammarAccess.getVideoSeqAccess().getDescAssignment_5_1(), "rule__VideoSeq__DescAssignment_5_1");
					put(grammarAccess.getVideoSeqAccess().getProbAssignment_6_1(), "rule__VideoSeq__ProbAssignment_6_1");
					put(grammarAccess.getMandatoryVideoSeqAccess().getVideoseqAssignment_1(), "rule__MandatoryVideoSeq__VideoseqAssignment_1");
					put(grammarAccess.getOptionalVideoSeqAccess().getVideoseqAssignment_1(), "rule__OptionalVideoSeq__VideoseqAssignment_1");
				}
			};
		}
		return nameMappings.get(element);
	}
	
	@Override
	protected Collection<FollowElement> getFollowElements(AbstractInternalContentAssistParser parser) {
		try {
			org.istic.idm.xtext.ui.contentassist.antlr.internal.InternalVideoGenParser typedParser = (org.istic.idm.xtext.ui.contentassist.antlr.internal.InternalVideoGenParser) parser;
			typedParser.entryRuleVideoGen();
			return typedParser.getFollowElements();
		} catch(RecognitionException ex) {
			throw new RuntimeException(ex);
		}		
	}
	
	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}
	
	public VideoGenGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(VideoGenGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
