/*
 * generated by Xtext
 */
package org.istic.idm.xtext.serializer;

import com.google.inject.Inject;
import java.util.List;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.xtext.IGrammarAccess;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.nodemodel.INode;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.AbstractElementAlias;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.TokenAlias;
import org.eclipse.xtext.serializer.analysis.ISyntacticSequencerPDAProvider.ISynNavigable;
import org.eclipse.xtext.serializer.analysis.ISyntacticSequencerPDAProvider.ISynTransition;
import org.eclipse.xtext.serializer.sequencer.AbstractSyntacticSequencer;
import org.istic.idm.xtext.services.VideoGenGrammarAccess;

@SuppressWarnings("all")
public class VideoGenSyntacticSequencer extends AbstractSyntacticSequencer {

	protected VideoGenGrammarAccess grammarAccess;
	protected AbstractElementAlias match_Sequence_UrlKeyword_3_0_0_0_q;
	protected AbstractElementAlias match_Statement_MandatoryKeyword_1_0_q;
	
	@Inject
	protected void init(IGrammarAccess access) {
		grammarAccess = (VideoGenGrammarAccess) access;
		match_Sequence_UrlKeyword_3_0_0_0_q = new TokenAlias(false, true, grammarAccess.getSequenceAccess().getUrlKeyword_3_0_0_0());
		match_Statement_MandatoryKeyword_1_0_q = new TokenAlias(false, true, grammarAccess.getStatementAccess().getMandatoryKeyword_1_0());
	}
	
	@Override
	protected String getUnassignedRuleCallToken(EObject semanticObject, RuleCall ruleCall, INode node) {
		if(ruleCall.getRule() == grammarAccess.getLEFT_BRACKETRule())
			return getLEFT_BRACKETToken(semanticObject, ruleCall, node);
		else if(ruleCall.getRule() == grammarAccess.getRIGHT_BRACKETRule())
			return getRIGHT_BRACKETToken(semanticObject, ruleCall, node);
		return "";
	}
	
	/**
	 * terminal LEFT_BRACKET: '{' ;
	 */
	protected String getLEFT_BRACKETToken(EObject semanticObject, RuleCall ruleCall, INode node) {
		if (node != null)
			return getTokenText(node);
		return "{";
	}
	
	/**
	 * terminal RIGHT_BRACKET: '}';
	 */
	protected String getRIGHT_BRACKETToken(EObject semanticObject, RuleCall ruleCall, INode node) {
		if (node != null)
			return getTokenText(node);
		return "}";
	}
	
	@Override
	protected void emitUnassignedTokens(EObject semanticObject, ISynTransition transition, INode fromNode, INode toNode) {
		if (transition.getAmbiguousSyntaxes().isEmpty()) return;
		List<INode> transitionNodes = collectNodes(fromNode, toNode);
		for (AbstractElementAlias syntax : transition.getAmbiguousSyntaxes()) {
			List<INode> syntaxNodes = getNodesFor(transitionNodes, syntax);
			if(match_Sequence_UrlKeyword_3_0_0_0_q.equals(syntax))
				emit_Sequence_UrlKeyword_3_0_0_0_q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if(match_Statement_MandatoryKeyword_1_0_q.equals(syntax))
				emit_Statement_MandatoryKeyword_1_0_q(semanticObject, getLastNavigableState(), syntaxNodes);
			else acceptNodes(getLastNavigableState(), syntaxNodes);
		}
	}

	/**
	 * Ambiguous syntax:
	 *     'url='?
	 *
	 * This ambiguous syntax occurs at:
	 *     description=STRING (ambiguity) url=STRING
	 *     length=INT (ambiguity) url=STRING
	 *     mimetype=Mimetypes_Enum (ambiguity) url=STRING
	 *     name=ID LEFT_BRACKET (ambiguity) url=STRING
	 *     url=STRING (ambiguity) url=STRING
	 */
	protected void emit_Sequence_UrlKeyword_3_0_0_0_q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     '@Mandatory'?
	 *
	 * This ambiguous syntax occurs at:
	 *     (rule start) (ambiguity) sequence=Sequence
	 */
	protected void emit_Statement_MandatoryKeyword_1_0_q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
}
