/*
 * generated by Xtext
 */
package org.istic.idm.xtext.ui.parser.antlr;

import org.antlr.runtime.Token;
import org.antlr.runtime.TokenSource;
import org.eclipse.xtext.parser.antlr.AbstractIndentationTokenSource;
import org.istic.idm.xtext.ui.contentassist.antlr.internal.InternalVideoGenParser;

public class VideoGenTokenSource extends AbstractIndentationTokenSource {
	
	public VideoGenTokenSource(TokenSource delegate) {
		super(delegate);
	}
	
	@Override
	protected boolean shouldSplitTokenImpl(Token token) {
		// TODO Review assumption
		return token.getType() == InternalVideoGenParser.RULE_WS;
	}

	@Override
	protected int getBeginTokenType() {
		// TODO Review assumption
		return InternalVideoGenParser.RULE_BEGIN;
	}

	@Override
	protected int getEndTokenType() {
		// TODO Review assumption
		return InternalVideoGenParser.RULE_END;
	}
	
	@Override
	protected boolean shouldEmitPendingEndTokens() {
		return false;
	}
	
}
