/**
 * generated by Xtext
 */
package org.istic.idm.xtext.validation;

import org.istic.idm.xtext.validation.AbstractVideoGenValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class VideoGenValidator extends AbstractVideoGenValidator {
}
